### ISSUE TITLE
请问后续有开源特征工程的计划吗？

### ISSUE THREAD

**Issue by m729448362** [JC-Shi/Learned-Index-Benefits#2]

**Comment by JC-Shi** [comment]
你好，感谢对这文章的兴趣。关于这个模型使用的特征工程的细节，可以参照文章中的第四章（4.2）。如果有什么问题，欢迎提问。谢谢。

**Comment by m729448362** [comment]
> 你好，感谢对这文章的兴趣。关于这个模型使用的特征工程的细节，可以参照文章中的第四章（4.2）。如果有什么问题，欢迎提问。谢谢。

好的，谢谢！

**Comment by m729448362** [comment]
请问特征工程中的基数是如何计算的？

**Comment by JC-Shi** [comment]
> 请问特征工程中的基数是如何计算的？

 你好，特征工程中基数是采用了初始执行计划（没有索引的情况下）中的估计值。谢谢。

**Comment by m729448362** [comment]
请问LIB目前能处理像in，like 这些关键词吗，他们也会用到索引吗？如果用到的话是属于scan_range还是scan_equal？

**Comment by JC-Shi** [comment]
> 请问LIB目前能处理像in，like 这些关键词吗，他们也会用到索引吗？如果用到的话是属于scan_range还是scan_equal？

LIB 目前无法处理 like 的关键词。因为目前支持的文本索引更多的只能支持从初始字母开始的检索。对于有比较复杂的pattern的like的检索语句，暂时没有索引支持。

对于包含 in 关键词的检索语句，LIB是支持的。如果基数较小，索引的使用会提升此类检索的效率。in的情况应该属于scan_equal，因为检索会基于in的条件来判断数据的值是否等于条件中的值。

**Comment by m729448362** [comment]
> > 请问LIB目前能处理像in，like 这些关键词吗，他们也会用到索引吗？如果用到的话是属于scan_range还是scan_equal？
> 
> LIB 目前无法处理 like 的关键词。因为目前支持的文本索引更多的只能支持从初始字母开始的检索。对于有比较复杂的pattern的like的检索语句，暂时没有索引支持。
> 
> 对于包含 in 关键词的检索语句，LIB是支持的。如果基数较小，索引的使用会提升此类检索的效率。in的情况应该属于scan_equal，因为检索会基于in的条件来判断数据的值是否等于条件中的值。

好的，谢谢！
