### ISSUE TITLE
请问业务场景不同的预训练模型效果好吗？

### ISSUE THREAD

**Issue by m729448362** [JC-Shi/Learned-Index-Benefits#3]
你好，在7.7 Adaption to Different Data Schema中测试了在TPC-DS-10GB中预训练，在TPC-DS-50GB中Fine-tuned，他们的表结构是一样的。请问有测试过类似在IMDB-JOB中预训练然后在TPC-DS或TPC-H中Fine-tuned吗？或者说如果我们金融数据库中预训练的模型，在运营商数据库中Fine-tuned有提升吗？谢谢！！！

**Comment by JC-Shi** [comment]
你好，在7.7中有展示在TPC-DS-10GB中预训练然后在IMDB-JOB和TPC-H中Fine-Tuned的模型表现。预训练模型的表现和postgresql的estimated cost based的what-if比可能只是稍微好一点甚至更差，但是fine-tuned之后效果会好很多，同时fine-tuned所需要的数据和时间会下降。希望对你有帮助，谢谢。

**Comment by m729448362** [comment]
> 你好，在7.7中有展示在TPC-DS-10GB中预训练然后在IMDB-JOB和TPC-H中Fine-Tuned的模型表现。预训练模型的表现和postgresql的estimated cost based的what-if比可能只是稍微好一点甚至更差，但是fine-tuned之后效果会好很多，同时fine-tuned所需要的数据和时间会下降。希望对你有帮助，谢谢。

好的，谢谢！orz
