### ISSUE TITLE
关于训练数据

### ISSUE THREAD

**Issue by m729448362** [JC-Shi/Learned-Index-Benefits#4]
你好，在Definition 1. Index Benefits的qj在无索引下的cost减去qj在有索引ci下的cost，在生成数据的时候比如在PG中，我需要同时在有索引和无索引的情况下执行explain analyze +sql吗？或者说无索引的cost只需要使用预估的cost？

**Comment by JC-Shi** [comment]
你好，无索引的cost也是explain analyze + sql的。

**Comment by m729448362** [comment]
> 你好，无索引的cost也是explain analyze + sql的。

在PG，是不会记录已执行的SQL的cost，如果我将预训练模型在真实客户场景中训练，收集的历史执行的带索引的SQL，必须重新真实的去执行一遍计算真实的cost吗？

**Comment by JC-Shi** [comment]
目前是这样的，因为如果用预测的（explain）的cost，训练出来不会修正optimizer的错误。

**Comment by m729448362** [comment]
> 目前是这样的，因为如果用预测的（explain）的cost，训练出来不会修正optimizer的错误。

好的，非常感谢！
