### ISSUE TITLE
您好，7-11是算子分类（分类的顺序是什么呢）？(join, sort, group, scan_range,scan_equal)这个顺序吗？

### ISSUE THREAD

**Issue by 18108851659-yzh** [JC-Shi/Learned-Index-Benefits#7]
你好，7-11是算子分类（分类的顺序是什么呢）？例如
[0, 1, 1, 9.392661928770137, 0.0, 1.0, 0, 0, 0, 0, 1, 4.852030263919617, 8.669055540725484]
算子顺序是论文提面的吗？ (join, sort, group, scan_range,scan_equal)这个顺序吗？

**Comment by JC-Shi** [comment]
Hello, thanks for the question. Regarding the features in position 7-11, it represents the operation type. The details are as follow: (7.scan_equal, scan_range, group, sort, 11.join).

**Comment by 18108851659-yzh** [comment]
多谢你的回答，请问下，（原始执行计划树和索引）转为特征向量的的源程序可以提供参考下吗？
